apiVersion: kafka.strimzi.io/v1beta2
kind: Kafka
metadata:
  name: kafka-cluster
  namespace: kafka
spec:
  kafka:
    version: 3.5.1
    replicas: 2
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 3
      min.insync.replicas: 1
      inter.broker.protocol.version: "3.5"
      log.retention.hours: 168
      log.cleanup.policy: "compact"
    logging:
      type: inline
      loggers:
        kafka.root.logger.level: ERROR
        log4j.logger.kafka.coordinator.transaction: ERROR
        log4j.logger.kafka.log.LogCleanerManager: ERROR
        log4j.logger.kafka.request.logger: ERROR
        log4j.logger.io.strimzi.kafka.oauth: ERROR
        log4j.logger.org.openpolicyagents.kafka.OpaAuthorizer: ERROR
    storage:
      type: jbod
      volumes:
        - id: 0
          type: persistent-claim
          size: 8Gi
          deleteClaim: false
  zookeeper:
    replicas: 1
    storage:
      type: persistent-claim
      size: 8Gi
      deleteClaim: false
  entityOperator:
    topicOperator: {}
    userOperator: {}
